/**
 * Responsibility: Provide a smart programming dogfood harness to verify ai-workflow capabilities.
 * Scope: Handles project initialization, recursive generation, verification, and efficiency metrics.
 */

import path from "node:path";
import { executeOperatorRequest } from "./operator-brain.ts";
import { getProjectSummary } from "./sync.ts";
import { writeProjectFile, readProjectFile, collectProjectFiles } from "../lib/filesystem.ts";

/**
 * Runs the dogfood harness for generating a modular emoji space-invaders-style 3d canvas game.
 */
export async function runDogfoodHarness(options = {}) {
  const root = options.root ?? process.cwd();
  const dogfoodRoot = path.join(root, "dogfood-projects", `space-invaders-${Date.now()}`);
  
  console.log(`[dogfood] Initializing dogfood project at: ${dogfoodRoot}`);
  
  // 1. Setup dogfood project (scaffold)
  const initialFiles = {
    "package.json": JSON.stringify({
      name: "dogfood-space-invaders",
      version: "0.1.0",
      type: "module",
      dependencies: {
        "three": "^0.160.0"
      }
    }, null, 2),
    "README.md": "# Space Invaders Dogfood Project\nGenerated by ai-workflow dogfood harness."
  };

  for (const [relativePath, content] of Object.entries(initialFiles)) {
    await writeProjectFile(dogfoodRoot, relativePath, content);
  }

  // 2. Generate the game (recursive shell call)
  const initialPrompt = `Generate a modular, expandable 3D canvas Space Invaders-style game with emoji ships. Use Three.js. 
Create separate modules for Engine, Entities, and UI. Add a main entry point that ties them together. 
You MUST write all code files now in this plan.

CRITICAL: Use REAL EMOJIS (e.g. 🚀, 👾) for graphics. 
Follow this pattern for entities:
\`\`\`javascript
export class EmojiShip {
  constructor(emoji = '🚀') {
    const canvas = document.createElement('canvas');
    canvas.width = 64; canvas.height = 64;
    const ctx = canvas.getContext('2d');
    ctx.font = '50px serif';
    ctx.fillText(emoji, 5, 50);
    const texture = new THREE.CanvasTexture(canvas);
    this.mesh = new THREE.Mesh(new THREE.PlaneGeometry(1, 1), new THREE.MeshBasicMaterial({ map: texture, transparent: true }));
  }
}
\`\`\``;
  
  let prompt = initialPrompt;  
  const startTime = Date.now();
  let attempts = 0;
  let ok = false;
  let verification = {};
  let lastResult = null;

  // Item: Model Escalation for complex dogfooding
  const highLogicPlanner = { providerId: "ollama", modelId: "hermes3:8b" };

  while (attempts < 3 && !ok) {
    attempts++;
    console.log(`[dogfood] Attempt ${attempts}: Generating/Fixing game...`);
    
    try {
      lastResult = await executeOperatorRequest(prompt, { 
        ...options, 
        root: dogfoodRoot,
        shellMode: "mutate",
        requestedWorkMode: "auto",
        planner: highLogicPlanner
      });

      if (!lastResult.ok) {
        console.log(`[dogfood] Generation failed: ${lastResult.assistantReply}. Retrying...`);
        prompt = `The previous attempt failed with error: ${lastResult.assistantReply}. Please try again, ensuring all required modules (Engine, Entities, UI) are created and correctly imported.`;
        continue;
      }
    } catch (error) {
      console.log(`[dogfood] Runtime error during generation: ${error.message}. Retrying...`);
      prompt = `The previous attempt crashed with error: ${error.message}. You likely tried to read or import a file that wasn't created yet. Ensure you CREATE all necessary files (src/engine.js, src/entities.js, src/ui.js, src/main.js) BEFORE trying to use them.`;
      continue;
    }

    // 3. Verify the game
    console.log("[dogfood] Verifying generation...");
    const generatedFiles = await collectProjectFiles(dogfoodRoot);
    const fileNames = generatedFiles;
    
    let hasEmojis = false;
    // Item: Recursive Search for Emojis in any entities file
    const entitiesFiles = fileNames.filter(f => /entities|ship|invader/i.test(f) && f.endsWith(".ts"));
    for (const f of entitiesFiles) {
      const file = await readProjectFile(dogfoodRoot, f).catch(() => null);
      if (file?.content && /[\u{1F300}-\u{1F9FF}\u{2600}-\u{26FF}]/u.test(file.content)) {
        hasEmojis = true;
        break;
      }
    }

    verification = {
      hasEngine: fileNames.some(f => /engine/i.test(f)),
      hasEntities: fileNames.some(f => /entities/i.test(f)),
      hasUI: fileNames.some(f => /ui/i.test(f)),
      hasMain: fileNames.some(f => /main|index/i.test(f)),
      hasEmojis,
      fileCount: fileNames.length,
      latencyMs: Date.now() - startTime,
      tokens: lastResult.plan?.usage?.totalTokens ?? 0,
      attempts
    };

    ok = verification.hasEngine && verification.hasEntities && verification.hasUI && verification.hasMain && verification.hasEmojis;

    if (!ok) {
      const missing = [];
      if (!verification.hasEngine) missing.push("Engine module");
      if (!verification.hasEntities) missing.push("Entities module");
      if (!verification.hasUI) missing.push("UI module");
      if (!verification.hasMain) missing.push("Main entry point");
      if (!verification.hasEmojis) missing.push("Emoji characters for ships");

      console.log(`[dogfood] Verification failed. Missing: ${missing.join(", ")}. Retrying with feedback...`);
      prompt = `The previous attempt failed verification. Missing items: ${missing.join(", ")}. 
CRITICAL: You MUST use emoji characters (e.g. 🚀, 👾) for graphics. Do NOT use standard 3D Box/Sphere cubes as shortcuts. 
Use the '3D Emoji Rendering' pattern from Lore: draw the emoji to a 2D canvas and use it as a THREE.CanvasTexture.`;
    }
  }

  const latency = Date.now() - startTime;

  // 4. Report metrics
  const report = {
    ok,
    timestamp: new Date().toISOString(),
    projectPath: dogfoodRoot,
    prompt,
    verification,
    summary: ok 
      ? `Dogfood generation completed in ${Math.round(latency / 1000)}s with ${verification.fileCount} files across ${attempts} attempt(s).`
      : `Dogfood generation failed after ${attempts} attempts.`
  };

  await writeProjectFile(root, ".ai-workflow/generated/dogfood-report.json", JSON.stringify(report, null, 2));
  
  return report;
}
