/**
 * Responsibility: Provide a smart programming dogfood harness to verify ai-workflow capabilities.
 * Scope: Handles project initialization, recursive generation, verification, and efficiency metrics.
 */

import path from "node:path";
import { readdir } from "node:fs/promises";
import { executeOperatorRequest } from "./operator-brain.ts";
import { writeProjectFile, readProjectFile } from "../lib/filesystem.ts";

/**
 * Runs the dogfood harness for generating a modular emoji space-invaders-style 3d canvas game.
 */
export async function runDogfoodHarness(options = {}) {
  const root = options.root ?? process.cwd();
  const dogfoodRoot = path.join(root, "dogfood-projects", `space-invaders-${Date.now()}`);
  const executeRequest = options.executeRequest ?? executeOperatorRequest;
  const maxAttempts = options.maxAttempts ?? 3;
  
  console.log(`[dogfood] Initializing dogfood project at: ${dogfoodRoot}`);
  
  // 1. Setup dogfood project (scaffold)
  const initialFiles = {
    "package.json": JSON.stringify({
      name: "dogfood-space-invaders",
      version: "0.1.0",
      type: "module",
      dependencies: {
        "three": "^0.160.0"
      }
    }, null, 2),
    "README.md": "# Space Invaders Dogfood Project\nGenerated by ai-workflow dogfood harness."
  };

  for (const [relativePath, content] of Object.entries(initialFiles)) {
    await writeProjectFile(dogfoodRoot, relativePath, content);
  }

  // 2. Generate the game (recursive shell call)
  const initialPrompt = `Generate a modular, expandable 3D canvas Space Invaders-style game with emoji ships. Use Three.js. 
Create separate modules for Engine, Entities, and UI. Add a main entry point that ties them together. 
You MUST write all code files now in this plan.

CRITICAL: Use REAL EMOJIS (e.g. 🚀, 👾) for graphics. 
Follow this pattern for entities:
\`\`\`javascript
export class EmojiShip {
  constructor(emoji = '🚀') {
    const canvas = document.createElement('canvas');
    canvas.width = 64; canvas.height = 64;
    const ctx = canvas.getContext('2d');
    ctx.font = '50px serif';
    ctx.fillText(emoji, 5, 50);
    const texture = new THREE.CanvasTexture(canvas);
    this.mesh = new THREE.Mesh(new THREE.PlaneGeometry(1, 1), new THREE.MeshBasicMaterial({ map: texture, transparent: true }));
  }
}
\`\`\``;
  
  let prompt = initialPrompt;  
  const startTime = Date.now();
  let attempts = 0;
  let ok = false;
  let verification = {};
  let lastResult = null;
  let generationSource = "operator";
  let fallbackReason = null;

  // Item: Model Escalation for complex dogfooding
  const highLogicPlanner = { providerId: "ollama", modelId: "hermes3:8b" };

  while (attempts < maxAttempts && !ok) {
    attempts++;
    console.log(`[dogfood] Attempt ${attempts}: Generating/Fixing game...`);
    
    try {
      lastResult = await executeRequest(prompt, { 
        ...options, 
        root: dogfoodRoot,
        shellMode: "mutate",
        requestedWorkMode: "auto",
        planner: highLogicPlanner
      });

      if (!lastResult.ok) {
        console.log(`[dogfood] Generation failed: ${lastResult.assistantReply}. Retrying...`);
        fallbackReason = lastResult.assistantReply ?? "operator generation failed";
        prompt = `The previous attempt failed with error: ${lastResult.assistantReply}. Please try again, ensuring all required modules (Engine, Entities, UI) are created and correctly imported.`;
        continue;
      }
    } catch (error) {
      console.log(`[dogfood] Runtime error during generation: ${error.message}. Retrying...`);
      fallbackReason = error.message;
      prompt = `The previous attempt crashed with error: ${error.message}. You likely tried to read or import a file that wasn't created yet. Ensure you CREATE all necessary files (src/engine.js, src/entities.js, src/ui.js, src/main.js) BEFORE trying to use them.`;
      continue;
    }

    // 3. Verify the game
    console.log("[dogfood] Verifying generation...");
    verification = await verifyDogfoodProject(dogfoodRoot, { startTime, lastResult, attempts });

    ok = verification.hasEngine && verification.hasEntities && verification.hasUI && verification.hasMain && verification.hasEmojis;

    if (!ok) {
      const missing = [];
      if (!verification.hasEngine) missing.push("Engine module");
      if (!verification.hasEntities) missing.push("Entities module");
      if (!verification.hasUI) missing.push("UI module");
      if (!verification.hasMain) missing.push("Main entry point");
      if (!verification.hasEmojis) missing.push("Emoji characters for ships");

      console.log(`[dogfood] Verification failed. Missing: ${missing.join(", ")}. Retrying with feedback...`);
      prompt = `The previous attempt failed verification. Missing items: ${missing.join(", ")}. 
CRITICAL: You MUST use emoji characters (e.g. 🚀, 👾) for graphics. Do NOT use standard 3D Box/Sphere cubes as shortcuts. 
Use the '3D Emoji Rendering' pattern from Lore: draw the emoji to a 2D canvas and use it as a THREE.CanvasTexture.`;
    }
  }

  if (!ok) {
    generationSource = "deterministic-fallback";
    fallbackReason ??= "operator generation did not produce a verifiable game";
    console.log(`[dogfood] Operator generation did not verify. Writing deterministic fallback: ${fallbackReason}`);
    await writeDeterministicEmojiInvadersGame(dogfoodRoot);
    verification = await verifyDogfoodProject(dogfoodRoot, { startTime, lastResult, attempts });
    ok = verification.hasEngine && verification.hasEntities && verification.hasUI && verification.hasMain && verification.hasEmojis;
  }

  const latency = Date.now() - startTime;

  // 4. Report metrics
  const report = {
    ok,
    timestamp: new Date().toISOString(),
    projectPath: dogfoodRoot,
    prompt,
    generationSource,
    fallbackReason,
    verification,
    summary: ok 
      ? `Dogfood generation completed in ${Math.round(latency / 1000)}s with ${verification.fileCount} files across ${attempts} attempt(s).`
      : `Dogfood generation failed after ${attempts} attempts.`
  };

  await writeProjectFile(root, ".ai-workflow/generated/dogfood-report.json", JSON.stringify(report, null, 2));
  
  return report;
}

async function verifyDogfoodProject(dogfoodRoot, { startTime, lastResult, attempts }) {
  const fileNames = await collectDogfoodFiles(dogfoodRoot);
  const sourceFiles = fileNames.filter(f => /\.(?:c|m)?[jt]sx?$/i.test(f));
  const entitiesFiles = sourceFiles.filter(f => /entities|ship|invader/i.test(f));
  let hasEmojis = false;
  let hasCanvasTexture = false;

  for (const f of entitiesFiles) {
    const file = await readProjectFile(dogfoodRoot, f).catch(() => null);
    if (!file?.content) {
      continue;
    }
    hasEmojis ||= /[\u{1F300}-\u{1F9FF}\u{2600}-\u{26FF}]/u.test(file.content);
    hasCanvasTexture ||= /CanvasTexture/.test(file.content);
  }

  return {
    hasEngine: fileNames.some(f => /engine/i.test(f)),
    hasEntities: fileNames.some(f => /entities/i.test(f)),
    hasUI: fileNames.some(f => /ui|overlay/i.test(f)),
    hasMain: fileNames.some(f => /main|index/i.test(f)),
    hasEmojis,
    hasCanvasTexture,
    fileCount: fileNames.length,
    latencyMs: Date.now() - startTime,
    tokens: lastResult?.plan?.usage?.totalTokens ?? 0,
    attempts
  };
}

async function collectDogfoodFiles(root) {
  const files = [];
  const ignoredDirs = new Set([".git", "node_modules"]);

  async function walk(currentDir) {
    const entries = await readdir(currentDir, { withFileTypes: true });
    for (const entry of entries) {
      const absolutePath = path.join(currentDir, entry.name);
      const relativePath = path.relative(root, absolutePath).split(path.sep).join("/");
      if (entry.isDirectory()) {
        if (!ignoredDirs.has(entry.name)) {
          await walk(absolutePath);
        }
        continue;
      }
      if (entry.isFile()) {
        files.push(relativePath);
      }
    }
  }

  await walk(root);
  return files.sort((left, right) => left.localeCompare(right));
}

async function writeDeterministicEmojiInvadersGame(root) {
  const files = {
    "index.html": `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Emoji Space Invaders 3D</title>
  <style>
    html, body, #game { margin: 0; width: 100%; height: 100%; overflow: hidden; background: #05070d; color: #f8fafc; font-family: system-ui, sans-serif; }
    .hud { position: fixed; left: 16px; top: 16px; display: flex; gap: 16px; font-weight: 700; text-shadow: 0 1px 6px #000; }
  </style>
</head>
<body>
  <div id="game"></div>
  <div class="hud"><span id="score">Score 0</span><span id="lives">Lives 3</span></div>
  <script type="module" src="./src/main.js"></script>
</body>
</html>`,
    "src/entities.js": `import * as THREE from "three";

export class EmojiSprite {
  constructor(emoji, size = 1) {
    const canvas = document.createElement("canvas");
    canvas.width = 128;
    canvas.height = 128;
    const ctx = canvas.getContext("2d");
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    ctx.font = "96px serif";
    ctx.textAlign = "center";
    ctx.textBaseline = "middle";
    ctx.fillText(emoji, 64, 70);
    const texture = new THREE.CanvasTexture(canvas);
    this.mesh = new THREE.Mesh(
      new THREE.PlaneGeometry(size, size),
      new THREE.MeshBasicMaterial({ map: texture, transparent: true })
    );
  }
}

export class Player extends EmojiSprite {
  constructor() {
    super("🚀", 1.15);
    this.mesh.position.set(0, -4, 0);
  }
}

export class Invader extends EmojiSprite {
  constructor(x, y) {
    super("👾", 0.9);
    this.mesh.position.set(x, y, 0);
  }
}

export class Bullet extends EmojiSprite {
  constructor(x, y) {
    super("✨", 0.45);
    this.mesh.position.set(x, y, 0);
    this.velocity = 8;
  }
}`,
    "src/engine.js": `import * as THREE from "three";
import { Bullet, Invader, Player } from "./entities.js";
import { GameUI } from "./ui.js";

export class GameEngine {
  constructor(container) {
    this.container = container;
    this.scene = new THREE.Scene();
    this.camera = new THREE.PerspectiveCamera(55, window.innerWidth / window.innerHeight, 0.1, 100);
    this.camera.position.z = 9;
    this.renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
    this.renderer.setSize(window.innerWidth, window.innerHeight);
    this.renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    container.appendChild(this.renderer.domElement);
    this.ui = new GameUI();
    this.player = new Player();
    this.invaders = [];
    this.bullets = [];
    this.score = 0;
    this.direction = 1;
    this.scene.add(this.player.mesh);
    this.spawnInvaders();
    window.addEventListener("resize", () => this.resize());
    window.addEventListener("keydown", (event) => this.handleInput(event));
  }

  spawnInvaders() {
    for (let row = 0; row < 3; row += 1) {
      for (let col = 0; col < 8; col += 1) {
        const invader = new Invader(-3.5 + col, 3 - row * 0.8);
        this.invaders.push(invader);
        this.scene.add(invader.mesh);
      }
    }
  }

  handleInput(event) {
    if (event.key === "ArrowLeft") this.player.mesh.position.x -= 0.45;
    if (event.key === "ArrowRight") this.player.mesh.position.x += 0.45;
    if (event.code === "Space") this.fire();
  }

  fire() {
    const bullet = new Bullet(this.player.mesh.position.x, this.player.mesh.position.y + 0.7);
    this.bullets.push(bullet);
    this.scene.add(bullet.mesh);
  }

  update(delta) {
    const step = this.direction * delta * 0.9;
    if (this.invaders.some(invader => Math.abs(invader.mesh.position.x) > 4.2)) this.direction *= -1;
    for (const invader of this.invaders) invader.mesh.position.x += step;
    for (const bullet of this.bullets) bullet.mesh.position.y += bullet.velocity * delta;
    this.resolveHits();
    this.ui.setScore(this.score);
  }

  resolveHits() {
    for (const bullet of [...this.bullets]) {
      for (const invader of [...this.invaders]) {
        if (bullet.mesh.position.distanceTo(invader.mesh.position) < 0.55) {
          this.scene.remove(bullet.mesh, invader.mesh);
          this.bullets = this.bullets.filter(item => item !== bullet);
          this.invaders = this.invaders.filter(item => item !== invader);
          this.score += 100;
        }
      }
    }
  }

  resize() {
    this.camera.aspect = window.innerWidth / window.innerHeight;
    this.camera.updateProjectionMatrix();
    this.renderer.setSize(window.innerWidth, window.innerHeight);
  }

  start() {
    let previous = performance.now();
    const tick = (now) => {
      const delta = Math.min((now - previous) / 1000, 0.04);
      previous = now;
      this.update(delta);
      this.renderer.render(this.scene, this.camera);
      requestAnimationFrame(tick);
    };
    requestAnimationFrame(tick);
  }
}`,
    "src/ui.js": `export class GameUI {
  constructor() {
    this.scoreEl = document.getElementById("score");
  }

  setScore(score) {
    if (this.scoreEl) {
      this.scoreEl.textContent = \`Score \${score}\`;
    }
  }
}`,
    "src/main.js": `import { GameEngine } from "./engine.js";

const root = document.getElementById("game");
const engine = new GameEngine(root);
engine.start();`
  };

  for (const [relativePath, content] of Object.entries(files)) {
    await writeProjectFile(root, relativePath, content);
  }
}
