/** Shared client instructions for MCP initialization and installed host guidance. */
export const PRIME_DIRECTIVE =
  'The simplest correct solution wins. Before adding any narrow rule, tool, abstraction, or special case, first look for the higher-level/general solution and existing primitive that already subsumes the problem; prefer that over brittle symptom patches. Reuse existing contracts and primitives before adding abstractions. Code should be no more complex than the problem. No duplicate or shadow systems, speculative compatibility layers, or branch proliferation. Make the smallest safe change, preserve working behavior, prove it, and merge/delete temporary branches at the first stable opportunity.';

export const REPOSITORY_INVESTIGATION =
  'Repository investigation & code edits: use AIWF even when no Ticket exists. Start with find_symbol (bounded name/file/kind filters) or get_file_outline for a known file, then get_symbol_source for the exact method/function. Use get_exact_callers/get_exact_references for TS/JS usage, search_graph for relationships, and analyze_blast_radius before edits. For code changes, ALWAYS use preview_change -> verify fingerprint -> apply_change; NEVER use generic/native file edit tools or whole-file writes. For a sibling repository, pass its projectRoot explicitly; filePath is relative to that project. An empty lookup is not proof of absence: check project scope and outline before falling back. Use bounded shell reads/searches only after an observed unsupported-file, missing-index or tool failure, and record that gap. Do not substitute whole-file dumps for available symbol slices.';

export const MCP_INSTRUCTIONS_2_0 =
  `Prime Directive: ${PRIME_DIRECTIVE}\nAIWF is the primary engineering and investigation interface. Delegate Ticket work first: call resolve_ticket first for implementation; use investigate_ticket/prepare_ticket for evidence/preparation and process_epic/process_feature/process_story for accepted intent. Inspect needs_input/blocked. Claim before manual edits, preserve user work, verify acceptance, release and sync.\n${REPOSITORY_INVESTIGATION}\nFor manual changes use preview_change then apply_change with its fingerprint. Tool schemas define parameters; use aiwf help for CLI syntax. No ceremonial Ticket is required for read-only source research.`;
